### ISSUE TITLE
Warns about @api values but Yardoc says it is freeform

### ISSUE THREAD

**Issue by gioele** [dkubb/yardstick#4]
Yardstick produces warnings like

> The @api tag must be either public, semipublic or private

but the the Yardoc guide says

> @api: Declares the API that the object belongs to. Does not display in output, but useful for performing queries (yardoc --query). Any text is allowable in this tag, and there are no predefined values(*).
> 
> @api freeform text
> 
> (*) Note that the special name @api private does display a notice in documentation if it is listed, letting users know that the method is not to be used.

At the same time, wouldn't it be better to suggest `@private` instead of `@api private`?

**Comment by aaronmallen** [comment]
@dkubb could you point me to a definition for these values, or add them to the documentation?  `public` and `private` are pretty apparent however what is `semipublic`.
